name: Build the Jar File
run-name: ${{ github.actor }} triggered a jar build
on: [ push ]
jobs:
  Build-Jar-File:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            **/.gradle*
            **/gradle-wrapper.properties
      - run: ./gradlew build
